const STATUS_CODE = {
    LOGIN_SUCCESS: 100,
    LOGIN_FAILED: 101,
    ADD_USER_SUCCESS: 102,
    ADD_USER_FAILED: 103,
    PASSWORD_VALIDATION_FAILED: 104,
    PASSWORD_HASHED_FAILED: 105,
    ADD_EMAIL_ALREADY_EXISTS: 106,
    NO_RESULT_FOUND: 107,
    PASSWORD_NOT_MATCH: 108,
    EMAIL_ADDRESS_REGEX: 109
}

export default STATUS_CODE;